---
title: "3. Maaslin2"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(phyloseq)
library(ggpubr)
library(haven)

stats = readxl::read_xlsx('Figure 4. Differential Abundance - Taxonomy.xlsx') %>% 
  filter(qval<0.05,Predictor==metadata)

p = readRDS('../Data/tax_glom/phylum.rds') %>% microbiome::transform('compositional') %>% 
  subset_taxa(Phylum %in% stats$taxon) %>% psmelt() %>% 
  pivot_longer(cols=c(PSS_36weeks,InternalizingPercentile),names_to = 'variable',values_to = 'value')
g = readRDS('../Data/tax_glom/genus.rds') %>%  microbiome::transform('compositional') %>% 
  subset_taxa(Genus %in% stats$taxon) %>% psmelt() %>% 
  pivot_longer(cols=c(PSS_36weeks,InternalizingPercentile),names_to = 'variable',values_to = 'value')

all_taxa = p %>% select(Sample,Phylum,Abundance,variable,value) %>% rename(Taxon = Phylum) %>% 
  mutate(Level = 'Phylum') %>% 
  rbind(g %>% select(Sample,Genus,Abundance,variable,value) %>% rename(Taxon = Genus) %>% mutate(Level = 'Genus')) %>% 
  mutate(variable = ifelse(variable == 'PSS_36weeks','PSS','IP')) %>% 
  mutate(variable = factor(.$variable, levels = c('PSS','IP')))%>% 
  mutate(Level = factor(.$Level, levels = c('Phylum','Genus'))) %>% 
  mutate(Taxon = str_sub(Taxon,start=4))
all_taxa$Taxon[all_taxa$Taxon=='[Ruminococcus]_torques_group'] = 'R. torques'
all_taxa$Taxon[all_taxa$Taxon=='[Eubacterium]_hallii_group'] = 'E. hallii'
all_taxa$Taxon[all_taxa$Taxon=='Clostridia_UCG-014'] = 'Clostridia UCG-014'
all_taxa$Taxon[all_taxa$Taxon=='UBA1819'] = 'Ruminococcaceae\nUBA1819'
all_taxa$Taxon[all_taxa$Taxon=='[Eubacterium]_coprostanoligenes_group'] = 'E. coprostanoligenes'
```

# Plots 

```{r}
plotlist = list()
plotlistlog = list()
for(i in unique(all_taxa$Taxon)){
  p = all_taxa %>% 
    filter(Taxon == i) %>% 
    ggplot(aes(value,Abundance,col=variable)) +
    geom_jitter(height=0,width=0.5) +
    geom_smooth(method='lm',col='black') +
    theme_classic(base_size=18) +
    ggh4x::facet_nested(Taxon~variable,scales = 'free') +
    theme(legend.position = 'none') +
    xlab(NULL)
  plotlist = append(plotlist,list(p))
  p = all_taxa %>% 
    filter(Taxon == i) %>% 
    mutate(pseudo = min(.$Abundance[.$Abundance>0])/2) %>% 
    mutate(log = log10(Abundance + pseudo)) %>% 
    ggplot(aes(value,log,col=variable)) +
    geom_jitter(height=0,width=0.5) +
    geom_smooth(method='lm',col='black') +
    theme_classic(base_size=18) +
    ggh4x::facet_nested(Taxon~variable,scales = 'free') +
    theme(legend.position = 'none') +
    xlab(NULL) + ylab('Log Abundance') +
    # ylim(-5,0)
    scale_y_continuous(expand = expansion(mult=0.1))
  plotlistlog = append(plotlistlog,list(p))
}
pp = ggarrange(plotlist = plotlist,ncol=2,nrow=4)
pplog = ggarrange(plotlist = plotlistlog,ncol=2,nrow=4)
ppmix = ggarrange(plotlist = list(plotlist[[1]],plotlist[[2]],
                                  plotlistlog[[3]],plotlistlog[[4]],
                                  plotlistlog[[5]],plotlistlog[[6]],
                                  plotlistlog[[7]],plotlistlog[[8]]),ncol=2,nrow=4)
```

# Save Plot

```{r}
ggsave('Figure S1. Scatterplots - Taxonomy.pdf',plot = pp,height=12,width=10,dpi=600)
ggsave('Figure S1. Scatterplots -  Log Taxonomy.pdf',plot=pplog,height=12,width=10,dpi=600)
ggsave('Figure S1. Scatterplots -  Mix Taxonomy.pdf',plot=ppmix,height=12,width=10,dpi=600)
```
