---
title: "3. Maaslin2"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(phyloseq)
library(ggpubr)
library(haven)

stats = readxl::read_xlsx('Figure 3. Differential Abundance - Metacyc.xlsx') %>% 
  filter(qval<0.05,Predictor==metadata) %>% 
  mutate(feature = str_sub(feature,start=2))

ps = readRDS('../CHILD_phyloseq_Feb25_metacyc.rds') %>% microbiome::transform('compositional') %>% 
  psmelt() %>% 
  mutate(feature = gsub("[[:punct:]]+", ".", .$Species)) %>% 
  filter(feature %in% stats$feature) %>% 
  pivot_longer(cols=c(PSS_36weeks,InternalizingPercentile),names_to = 'variable',values_to = 'value') %>% 
  mutate(variable = ifelse(variable == 'PSS_36weeks','PSS','IP')) %>% 
  mutate(variable = factor(.$variable, levels = c('PSS','IP')))
# All accounted for
table(unique(stats$feature) %in% unique(ps$feature))
```

# Plots 

```{r}
plotlist = list()
plotlistlog = list()
for(i in unique(ps$feature)){
  p = ps %>% 
    filter(feature == i) %>% 
    ggplot(aes(value,Abundance,col=variable)) +
    geom_jitter(height=0,width=0.5) +
    geom_smooth(method='lm',col='black') +
    theme_classic(base_size=18) +
    ggh4x::facet_nested(feature~variable,scales = 'free') +
    theme(legend.position = 'none') +
    xlab(NULL)
  plotlist = append(plotlist,list(p))
  p = ps %>% 
    filter(feature == i) %>% 
    mutate(pseudo = min(.$Abundance[.$Abundance>0])/2) %>% 
    mutate(log = log10(Abundance + pseudo)) %>% 
    ggplot(aes(value,log,col=variable)) +
    geom_jitter(height=0,width=0.5) +
    geom_smooth(method='lm',col='black') +
    theme_classic(base_size=18) +
    ggh4x::facet_nested(feature~variable,scales = 'free') +
    theme(legend.position = 'none') +
    xlab(NULL) + ylab('Log Abundance') +
    # ylim(-5,0)
    scale_y_continuous(expand = expansion(mult=0.1))
  plotlistlog = append(plotlistlog,list(p))
}
pp = ggarrange(plotlist = plotlist,ncol=3,nrow=9)
pplog = ggarrange(plotlist = plotlistlog,ncol=3,nrow=9)
# ppmix = ggarrange(plotlist = list(plotlist[[1]],plotlist[[2]],
#                                   plotlistlog[[3]],plotlistlog[[4]],
#                                   plotlistlog[[5]],plotlistlog[[6]],
#                                   plotlistlog[[7]],plotlistlog[[8]]),ncol=2,nrow=4)
```

# Save Plot

```{r}
ggpubr::ggexport(plotlist = unname(plotlist),
         filename = "Figure S3. Scatterplots - Metacyc.pdf",
         ncol = 2, nrow = 4,
         width = 10, height = 14,
         multipage = TRUE)

ggpubr::ggexport(plotlist = unname(plotlistlog),
         filename = "Figure S3. Scatterplots - Log Metacyc.pdf",
         ncol = 2, nrow = 4, 
         width = 10, height = 14,  
         multipage = TRUE)
```
