---
title: "Figure 5. Differential Abundance - MetaCyc"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(phyloseq)
library(ggpubr)
library(lavaan)
library(manymome)
library(haven)
library(Maaslin2)

meta = read_sav('../Data/CHILD_CBCL_MatDistress_Microbiome_09042024_ForAvril.sav')
ps = readRDS('../CHILD_phyloseq_Feb25_metacyc.rds')

# Fix metadata
meta$csec[meta$csec=='NA'] = NA
meta$csec[meta$csec==''] = NA
table(is.na(meta$csec))
table(meta$csec)

meta$Mother_abs_birth_yn[meta$Mother_abs_birth_yn=='NA'] = NA
meta$Mother_abs_birth_yn[meta$Mother_abs_birth_yn==''] = NA
table(is.na(meta$Mother_abs_birth_yn))
table(meta$Mother_abs_birth_yn)

# Fix breast milk variables
meta$bf_3m = sapply(meta$BF_3m_status_4, function(x){
  return(ifelse(is.na(x),NA,ifelse(x=='',NA,
                                   ifelse(x=='Never breastfed','No', ifelse(x=='Zero','Prev','Yes')))))
})
meta$bf_3m = factor(meta$bf_3m, levels = c('No','Prev','Yes'))
meta$bf_3m_bool = meta$bf_3m
meta$bf_3m_bool[meta$bf_3m_bool=='Prev'] = 'No'
meta$BF_12m[meta$BF_12m=='' | meta$BF_12m=='NA'] = NA
meta$BF_dur = sapply(meta$BF_dur_cat2, function(x){
  return(ifelse(is.na(x),NA,ifelse(x=='Never breastfed',0,
                                   ifelse(x=='>0-3',1, ifelse(x=='3-9',2,ifelse(x=='9-12',3,4))))))
})

psmeta = prune_taxa(taxa_names(ps)[1],ps) %>% psmelt()

ps@sam_data$depth = scale(sample_sums(ps))

ps@sam_data = prune_taxa(taxa_names(ps)[1],ps) %>% psmelt() %>% 
  select(-OTU,-Abundance,-Species) %>% 
  left_join(psmeta %>% select(Sample,BF_dur,bf_3m_bool) %>% unique()) %>% 
  column_to_rownames('Sample') %>% sample_data()
```

```{r Load significant functions}
da_results = readxl::read_xlsx('Figure 3. Differential Abundance - MetaCyc.xlsx') %>% 
  filter(sig==1, metadata == Predictor, Group=='1 year') 
  
annot = readxl::read_xlsx('Figure 3. Differential Abundance - MetaCyc.xlsx',sheet='Annotations') %>% unique()

# Only plot the strongest correlations from each group:
strongest = da_results %>% 
  left_join(annot) %>% 
  group_by(group) %>% 
  arrange(pval) %>% 
  filter(feature==feature[1L]) %>% ungroup() %>% 
  mutate(feature = str_sub(feature,start=2))
```

# Mediation

```{r}
pmelt = ps %>% microbiome::transform('compositional')
taxa_names(pmelt) = str_replace_all(taxa_names(pmelt),'-','.') %>% str_replace_all('[+]','.')
pmelt = prune_taxa(strongest$feature,pmelt) %>% subset_samples(Visit=='1year') %>% psmelt()

pmelt = pmelt %>% 
  group_by(Species) %>% 
  mutate(ZAbundance = scale(Abundance)) %>% 
  ungroup() %>% 
  select(Participant_ID,Dyad_ID,Sample,ZAbundance,Species,depth) %>% 
  right_join(meta) %>% 
  droplevels()
```

```{r}
stats.med = tibble()
to_test = unique(pmelt$Species)[!is.na(unique(pmelt$Species))]
for(x in to_test){
  # x = pmelt$Species[1]
  # Univariate
  Model <-'
  ZInternalizingPercentile ~ ZAbundance
  ZAbundance ~ ZPSS_36weeks
  '

  set.seed(421)
  Modelrun <- sem(Model, data= pmelt %>% filter(Species==x), fixed.x=TRUE, missing="ml")
  summary(Modelrun, standardized=TRUE,fit.measures=TRUE, rsquare=TRUE)


  ModelIE <- indirect_effect(x = "ZPSS_36weeks",
                             y = "ZInternalizingPercentile",
                             m = "ZAbundance",
                             fit = Modelrun,
                             boot_ci = TRUE,
                             R = 500,
                             ncores=1,
                             seed=421)

  modelout = print(ModelIE,pvalue=TRUE)

  stats.med = rbind(stats.med,
                    tibble(Level='MetaCyc',Time = '1 year',Type='Univariable',Taxon=x,
                     Estimate = modelout$indirect,
                     Estimate_low = modelout$boot_ci[1],
                     Estimate_high = modelout$boot_ci[2],
                     Pval = modelout$boot_p,
                     SE = modelout$boot_se)
  )
  
  # Multivariate
  Model <- '
  # Mediation paths
  ZInternalizingPercentile ~ ZAbundance
  ZAbundance ~ ZPSS_36weeks

  # Direct paths for the predictors
  ZAbundance ~ Mother_abs_birth_yn + csec + BF_dur + depth
  '
  
  set.seed(421)
  Modelrun <- sem(Model, data=pmelt %>% filter(Species==x), fixed.x=TRUE, missing="ml")
  summary(Modelrun, standardized=TRUE,fit.measures=TRUE, rsquare=TRUE)
  
  
  ModelIE <- indirect_effect(x = "ZPSS_36weeks",
                             y = "ZInternalizingPercentile",
                             m = "ZAbundance",
                             fit = Modelrun,
                             boot_ci = TRUE,
                             R = 500,
                             ncores=1,
                             seed=421)
  
  modelout = print(ModelIE,pvalue=TRUE)
  
  stats.med = rbind(stats.med,
                    tibble(Level='MetaCyc',Time = '1 year',Type='Multivariable',Taxon=x,
                     Estimate = modelout$indirect,
                     Estimate_low = modelout$boot_ci[1],
                     Estimate_high = modelout$boot_ci[2],
                     Pval = modelout$boot_p,
                     SE = modelout$boot_se)
  )
}

stats.med = stats.med %>% 
  group_by(Level,Type) %>% 
  mutate(Padj = p.adjust(Pval,method='BH')) %>% 
  ungroup()
```

```{r Save stats}
writexl::write_xlsx(list(Mediation=stats.med),'Table 3b. MetaCyc Mediation.xlsx')
```